### ISSUE TITLE
MPI_Allreduce use same memory address for src and dst.

### ISSUE THREAD

**Issue by syoyo** [avr-aics-riken/HDMlib#5]
In https://github.com/avr-aics-riken/HDMlib/blob/master/src/ErrorUtil.cpp#L24 src buf and dst buf are same, resulting in the following runtime error with Intel MPI environment.

```
MPI_Allreduce(1325): MPI_Allreduce(sbuf=0x7fffffffb800, rbuf=0x7fffffffb800, count=1, MPI_INT, MPI_BOR, MPI_COMM_WORLD) failed
MPI_Allreduce(1294): Buffers must not be aliased
```

OpenMPI looks it arrow `src buf == dst buf` http://www.open-mpi.org/doc/v1.5/man3/MPI_Allreduce.3.php , but mpich(Intel MPI) looks not http://www.mpich.org/static/docs/v3.1/www3/MPI_Allreduce.html

**Comment by kenoogl** [comment]
fix this issue by,
    bool ErrorUtil::reduceError(const bool err, MPI::Intracomm& comm) {
        int ierr_s = err ? 1 : 0;
    int ierr_r = ierr_s;
        comm.Allreduce(&ierr_s, &ierr_r, 1, MPI::INT, MPI::BOR);
        return ierr_r == 0 ? false : true;
    }
